# Generated by Django 4.2.13 on 2025-05-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='email_comprador',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_comprador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono_comprador',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='000000', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_disponible',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
