# Generated by Django 4.2.13 on 2025-07-04 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_api', '0005_pedido_precio_unitario_pedido_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='transferenciaproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='transferenciaproducto',
            name='sucursal_destino',
        ),
        migrations.RemoveField(
            model_name='transferenciaproducto',
            name='sucursal_origen',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_inventario_api', to='inventario_api.producto'),
        ),
        migrations.DeleteModel(
            name='InventarioSucursal',
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
        migrations.DeleteModel(
            name='TransferenciaProducto',
        ),
    ]
