# Generated by Django 4.2.13 on 2025-07-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleboleta',
            name='producto',
        ),
        migrations.AddField(
            model_name='detalleboleta',
            name='imagen_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='detalleboleta',
            name='nombre_producto',
            field=models.CharField(default='Producto desconocido', max_length=255),
        ),
        migrations.AddField(
            model_name='detalleboleta',
            name='producto_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detalleboleta',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detalleboleta',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
