# Generated by Django 4.2.13 on 2025-05-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='ciudad',
            field=models.CharField(default='Santiago', max_length=100),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='region',
            field=models.CharField(default='Metropolitana', max_length=100),
        ),
    ]
