# Generated by Django 4.2.13 on 2025-05-28 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_api', '0001_initial'),
        ('pedido_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_pedido_api', to='inventario_api.producto'),
        ),
    ]
